use serde_json::{json, Value};
use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;

fn module_dir() -> PathBuf {
    if let Some(d) = std::env::var_os("KMGR_MODULE_DIR") {
        return PathBuf::from(d);
    }
    if let Ok(exe) = std::env::current_exe() {
        if let Some(bin) = exe.parent() {
            if let Some(m) = bin.parent() {
                return m.to_path_buf();
            }
        }
    }
    PathBuf::from("/data/adb/modules/kmgr")
}

fn system_prop() -> PathBuf {
    module_dir().join("system.prop")
}

fn getprop_all() -> BTreeMap<String, String> {
    let mut m = BTreeMap::new();
    if let Ok(out) = std::process::Command::new("getprop").output() {
        for line in String::from_utf8_lossy(&out.stdout).lines() {
            let line = line.trim();
            if let Some(rest) = line.strip_prefix('[') {
                if let Some((k, v)) = rest.split_once("]: [") {
                    if let Some(v) = v.strip_suffix(']') {
                        m.insert(k.to_string(), v.to_string());
                    }
                }
            }
        }
    }
    m
}

fn load_overrides() -> BTreeMap<String, String> {
    let mut m = BTreeMap::new();
    if let Ok(s) = std::fs::read_to_string(system_prop()) {
        for line in s.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some((k, v)) = line.split_once('=') {
                m.insert(k.trim().to_string(), v.trim().to_string());
            }
        }
    }
    m
}

fn save_overrides(m: &BTreeMap<String, String>) {
    let mut s = String::from(
        "# Generated by the Kernel Manager WebUI. Reboot required for changes to take effect.\n",
    );
    for (k, v) in m {
        s.push_str(&format!("{}={}\n", k, v));
    }
    let _ = std::fs::create_dir_all(module_dir());
    let _ = std::fs::write(system_prop(), s);
}

fn valid_key(k: &str) -> bool {
    !k.is_empty()
        && k.chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '_' || c == '-')
}

fn valid_value(v: &str) -> bool {
    !v.contains('\n') && !v.contains('\r')
}

pub fn list(query: &str) -> Value {
    let props = getprop_all();
    let ov = load_overrides();
    let q = query.trim().to_lowercase();
    let mut items: Vec<Value> = Vec::new();
    let mut seen: BTreeSet<String> = BTreeSet::new();

    for (k, v) in &props {
        if !q.is_empty() && !k.to_lowercase().contains(&q) {
            continue;
        }
        items.push(json!({"key": k, "value": v, "overridden": ov.contains_key(k)}));
        seen.insert(k.clone());
    }
    for (k, v) in &ov {
        if seen.contains(k) || (!q.is_empty() && !k.to_lowercase().contains(&q)) {
            continue;
        }
        items.push(json!({"key": k, "value": v, "overridden": true}));
    }

    let total = items.len();
    // items.truncate(500);
    json!({"ok": true, "props": items, "total": total})
}

pub fn set(key: &str, value: &str) -> Value {
    if !valid_key(key) {
        return json!({"ok": false, "error": "invalid property key"});
    }
    if !valid_value(value) {
        return json!({"ok": false, "error": "invalid property value"});
    }
    let mut ov = load_overrides();
    ov.insert(key.to_string(), value.to_string());
    save_overrides(&ov);
    json!({"ok": true, "reboot_required": true})
}

pub fn unset(key: &str) -> Value {
    let mut ov = load_overrides();
    ov.remove(key);
    save_overrides(&ov);
    json!({"ok": true, "reboot_required": true})
}

pub fn reset() -> Value {
    save_overrides(&BTreeMap::new());
    json!({"ok": true, "reboot_required": true})
}
